# MySQLDBConfig
mysql_user: "my2lite"
mysql_pwd: "7d7916fa8ece01f0110744d22d0e527476ab202fbaca0e48c244d24b37b5af2f"
mysql_addr: "127.0.0.1"
mysql_port: "3306"
mysql_db: "mytongdy_archive"
mysql_limit: "100"
mysql_table: "data_original_read_2021"
# SQLiteConfig
sqlite_ver: "sqlite3"
sqlite_db: "P:/go/src/github.com/kagurazakayashi/My2LiteDump/data_original_read_2021.db"
